### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [zahmryan/my_db_app_users#1]
I think you may have misunderstood this criterion:

> NOT display any links to unauthorized actions to anonymous visitors (such as links to create a new record, edit a record, or delete a record)

I would still like to see a link to the list of movie stores when not signed in, since anonymous visitors are allowed to visit the `index` and `show` actions. It's just links to the other actions (that users are not authorized to use) that I'd like hidden. Let me know if that makes sense.

**Comment by zahmryan** [comment]
Fixed, anonymous users can see the moviestore link but can no longer edit, delete or create a new one

**Comment by chrisvfritz** [comment]
:+1: Looks good!
